### PR TITLE
Notebook example files added for ECM and folder structure updated.

### LINKED ISSUE #437: Add Thermal Thevenin Example (Remove Params from Others)
This issue is to remove the thermal parameters from non-thermal Thevenin examples: https://github.com/pybop-team/PyBOP/blob/9e15f90b75c4f5fb04cb17c0807dd0b5e1a2e6fb/examples/scripts/ecm_CMAES.py#L24

At the sametime, let's add a Thevenin with thermal submodel example with those corresponding parameters. For more information on PyBaMM's thermal submodel see: https://docs.pybamm.org/en/latest/source/examples/notebooks/models/thermal-models.html

### PR DESCRIPTION
**Pull request by Dibyendu-IITKGP**
# Description

Notebook example files are added for single pulse and multi-pulse HPPC data fitting, a thermal submodel is also added. Folder structure updated to keep data files for running example notebook files.

## Issue reference
Fixes #437 

## Review
Before you mark your PR as ready for review, please ensure that you've considered the following:
- Updated the [CHANGELOG.md](https://github.com/pybop-team/PyBOP/blob/develop/CHANGELOG.md) in reverse chronological order (newest at the top) with a concise description of the changes, including the PR number.
- Noted any breaking changes, including details on how it might impact existing functionality.

## Type of change
- [ ] New Feature: A non-breaking change that adds new functionality.
- [ ] Optimization: A code change that improves performance.
- [x] Examples: A change to existing or additional examples.
- [ ] Bug Fix: A non-breaking change that addresses an issue.
- [ ] Documentation: Updates to documentation or new documentation for new features.
- [ ] Refactoring: Non-functional changes that improve the codebase.
- [ ] Style: Non-functional changes related to code style (formatting, naming, etc).
- [ ] Testing: Additional tests to improve coverage or confirm functionality.
- [ ] Other: (Insert description of change)

# Key checklist:

- [ ] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybop-team/PyBOP/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [ ] All unit tests pass: `$ nox -s tests`
- [ ] The documentation builds: `$ nox -s doctest`

You can run integration tests, unit tests, and doctests together at once, using `$ nox -s quick`.

## Further checks:
- [ ] Code is well-commented, especially in complex or unclear areas.
- [ ] Added tests that prove my fix is effective or that my feature works.
- [ ] Checked that coverage remains or improves, and added tests if necessary to maintain or increase coverage.

Thank you for contributing to our project! Your efforts help us to deliver great software.

### CODE REVIEW

**Comment by BradyPlanden** [comment]
I thought we had a stale PR diff for `examples/data/LG_M50_ECM/1-single-pulse-circuit-model.ipynb`, but due to the movement of this file to `data` directory, the current state of it on develop is different than the state in this branch. I don't believe you changed this notebook(?), so this needs to be updated to reflect the current state in develop.

**Comment by Dibyendu-IITKGP** [comment]
Yes, I haven't changed this file. So you mean this file needs to be pushed as a commit?

**Comment by BradyPlanden** [comment]
Yes, one way is to restore the notebook to develop state and move it again before committing. The below command should restore the file to develop state.

```bash
git restore -s develop examples/notebooks/LG_M50_ECM/1-single-pulse-circuit-model.ipynb
```

**Comment by Dibyendu-IITKGP** [comment]
Great, thanks!

**Comment by Dibyendu-IITKGP** [comment]
I think now we are good to go.

**Review by BradyPlanden — APPROVED** [review]
Thanks for these additions @Dibyendu-IITKGP - they look great! I'll merge once the tests finish.

**Comment by BradyPlanden** [comment]
@all-contributors please add @Dibyendu-IITKGP for examples

**Pull request merged**
