### PR TITLE
Add electrode balancing example

### LINKED ISSUE #222: Add electrode balancing example
### Feature description

Create an example workflow for fitting the electrode stoichiometry balance parameters from pseudo-OCV test data.

### Motivation

To demonstrate and benchmark a common battery parameterisation problem.

### Possible implementation

This could be implemented as an example script/notebook or as an extension of the FittingProblem class.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by brosaplanella**
# Description

Added an example for electrode balancing. The main issue was defining the model, for now I have hacked it via an ECM but this means we can only balance half cells. In the future it would be interesting to define specific models for electrode balancing, which could support full cells too.

## Issue reference
Fixes #222 

## Review
Before you mark your PR as ready for review, please ensure that you've considered the following:
- Updated the [CHANGELOG.md](https://github.com/pybop-team/PyBOP/blob/develop/CHANGELOG.md) in reverse chronological order (newest at the top) with a concise description of the changes, including the PR number.
- Noted any breaking changes, including details on how it might impact existing functionality.

## Type of change
- [ ] New Feature: A non-breaking change that adds new functionality.
- [ ] Optimization: A code change that improves performance.
- [x] Examples: A change to existing or additional examples.
- [ ] Bug Fix: A non-breaking change that addresses an issue.
- [ ] Documentation: Updates to documentation or new documentation for new features.
- [ ] Refactoring: Non-functional changes that improve the codebase.
- [ ] Style: Non-functional changes related to code style (formatting, naming, etc).
- [ ] Testing: Additional tests to improve coverage or confirm functionality.
- [ ] Other: (Insert description of change)

# Key checklist:

- [ ] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybop-team/PyBOP/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [ ] All unit tests pass: `$ nox -s tests`
- [ ] The documentation builds: `$ nox -s doctest`

You can run integration tests, unit tests, and doctests together at once, using `$ nox -s quick`.

## Further checks:
- [x] Code is well-commented, especially in complex or unclear areas.
- [ ] Added tests that prove my fix is effective or that my feature works.
- [ ] Checked that coverage remains or improves, and added tests if necessary to maintain or increase coverage.

Thank you for contributing to our project! Your efforts help us to deliver great software.

### CODE REVIEW

**Comment by NicolaCourtier** [comment]
Thanks @brosaplanella, I like your use of the Thevenin model in this example, but unfortunately it doesn't seem to work on the `develop` branch - probably due to my changes to `set_initial_state`. Let me know if you'd like me to look into this.

**Comment by brosaplanella** [comment]
I just merged develop and the tests are passing. The only one that breaks it the Lychee one, as for some reason it picks up a string I define in the notebook that is not complete (I append the extra bit later on). Not sure if there is a way to tell Lychee to ignore that (@agriyakhetarpal might know). Otherwise, I will hardcode each of the URLs which should make the test pass.

**Comment by NicolaCourtier** [comment]
It passes when pip installing from `main`. To see what I mean, set up the environment with:
`%pip install git+https://github.com/pybop-team/PyBOP@develop --force-reinstall -q`

**Comment by BradyPlanden** [comment]
> Not sure if there is a way to tell Lychee to ignore that 

Yes, you can add an exclusion for the broken link to the Lychee workflow file: https://github.com/pybop-team/PyBOP/blob/1a764707687de91db7ff39e607ab46f3502eaa81/.github/workflows/lychee_links.yaml#L39

It would look like this: 
`--exclude "https://raw.githubusercontent.com/paramm-team/pybamm-param/develop/pbparam/input/data/"`

**Comment by brosaplanella** [comment]
I have now made Lychee ignore the incomplete URL so it passes. About the issue with develop branch, I tried creating a new virtual environment and installing the develop branch and the example still runs as expected. I also double checked and the GitHub actions should install the version in the tested branch, which I have now made sure is up-to-date with develop. If someone else try to reproduce Nicola's that would be great!

**Comment by NicolaCourtier** [comment]
Thanks for the update! I tested again and now think the issue may not be due to the branch, just some initial values. Please could you try an initial soc >= 0.5 and capacity >= 50? In my case, `SciPyMinimize` terminates before locating the minimum, so it may be worth amending the parameter bounds for robustness.

Other than that, just two things, please:
- fix typo on the first line
- add `fig.show()` at the end, to include the plot in the preview

**Review by NicolaCourtier — APPROVED** [review]
Nice work, thanks @brosaplanella !

**Review by BradyPlanden — APPROVED** [review]
Looks great, thanks @brosaplanella! The bottom figure will be correctly rendered when #410 lands with nbviewer, so that should be sorted soon.

**Pull request merged**
