### PR TITLE
#238 multiple datasets

### PR DESCRIPTION
**Pull request by MarkBlyth**
# Description

Towards implementing multiple models and multiple datasets. fitting_problem now evaluates to give a list of solutions, one per model/dataset pair. Cost functions weight each error-set to get an overall error score, which is then optimised against. Draft PR, not fully tested and with open todos.

## Issue reference
#238 

## Type of change
- [ x ] New Feature: A non-breaking change that adds new functionality.
- [ ] Optimization: A code change that improves performance.
- [ ] Examples: A change to existing or additional examples.
- [ ] Bug Fix: A non-breaking change that addresses an issue.
- [ ] Documentation: Updates to documentation or new documentation for new features.
- [ ] Refactoring: Non-functional changes that improve the codebase.
- [ ] Style: Non-functional changes related to code style (formatting, naming, etc).
- [ ] Testing: Additional tests to improve coverage or confirm functionality.
- [ ] Other: (Insert description of change)

# Key checklist:

- [ ] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybop-team/PyBOP/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [ ] All unit tests pass: `$ nox -s tests`
- [ ] The documentation builds: `$ nox -s doctest`

You can run integration tests, unit tests, and doctests together at once, using `$ nox -s quick`.

## Further checks:
- [x ] Code is well-commented, especially in complex or unclear areas.
- [ ] Added tests that prove my fix is effective or that my feature works.
- [ ] Checked that coverage remains or improves, and added tests if necessary to maintain or increase coverage.

Thank you for contributing to our project! Your efforts help us to deliver great software.

### CODE REVIEW

**Comment by BradyPlanden** [comment]
Hi @MarkBlyth, thanks for this! I'll try to take a look through this afternoon or Monday morning 👍

**Comment by NicolaCourtier** [comment]
Hi @MarkBlyth, I made a start on developing a cost wrapper for multiple cost objects to demonstrate what I meant in point (2) above - see issue #327 and the draft PR #329. I'd be happy to discuss pros/cons of different approaches.

**Review by NicolaCourtier — COMMENTED** [review]
Hi @MarkBlyth, would you be interested in recreating this functionality with the new `MultiFittingProblem` and `WeightedCost`?

**Comment by MarkBlyth** [comment]
@NicolaCourtier yep sounds good! I won't be able to put too much time into it until after the FI conference, but I'm keen to do some work on it.

**Comment by NicolaCourtier** [comment]
I think this work has fallen too far out-of-date and it will be easier to re-implement the changes in a new branch, so I will close this PR for now. Some of the features have also been addressed in other PRs e.g. 329.

**Pull request closed without merging**
