### PR TITLE
Refactor problems

### LINKED ISSUE #279: Refactor problems into different files
Refactor the classes in `_problem.py` into several files. It is already part of #249 but separating it here to avoid conflicts every time a new branch is merged to develop.

### PR DESCRIPTION
**Pull request by brosaplanella**
# Description

Refactor the various problem classes into separate folders.

## Issue reference
Fixes #279

## Review
Before you mark your PR as ready for review, please ensure that you've considered the following:
- Updated the [CHANGELOG.md](https://github.com/pybop-team/PyBOP/blob/develop/CHANGELOG.md) in reverse chronological order (newest at the top) with a concise description of the changes, including the PR number.
- Noted any breaking changes, including details on how it might impact existing functionality.

## Type of change
- [ ] New Feature: A non-breaking change that adds new functionality.
- [ ] Optimization: A code change that improves performance.
- [ ] Examples: A change to existing or additional examples.
- [ ] Bug Fix: A non-breaking change that addresses an issue.
- [ ] Documentation: Updates to documentation or new documentation for new features.
- [x] Refactoring: Non-functional changes that improve the codebase.
- [ ] Style: Non-functional changes related to code style (formatting, naming, etc).
- [ ] Testing: Additional tests to improve coverage or confirm functionality.
- [ ] Other: (Insert description of change)

# Key checklist:

- [x] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybop-team/PyBOP/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [x] All unit tests pass: `$ nox -s tests`
- [x] The documentation builds: `$ nox -s doctest`

You can run integration tests, unit tests, and doctests together at once, using `$ nox -s quick`.

## Further checks:
- [x] Code is well-commented, especially in complex or unclear areas.
- [ ] Added tests that prove my fix is effective or that my feature works.
- [x] Checked that coverage remains or improves, and added tests if necessary to maintain or increase coverage.

Thank you for contributing to our project! Your efforts help us to deliver great software.

### CODE REVIEW

**Comment by brosaplanella** [comment]
As this is refactoring, let me know if it should have a line in the CHANGELOG or not (and under which category).

**Comment by BradyPlanden** [comment]
Thanks for the addition @brosaplanella!

Unforunately, this is currently blocked as the codecov is silently failing. A fix for this is in #275, if you want to add that fix to this branch I'm happy to review. Otherwise I'll review once we've merged #275 and this branch merges develop.

**Comment by BradyPlanden** [comment]
LGTM, thanks for the addition @brosaplanella!

**Review by BradyPlanden — APPROVED** [review]

**Comment by BradyPlanden** [comment]
@all-contributors add @brosaplanella to code

**Pull request merged**
