### PR TITLE
Fix for nightly dependancy workflow

### LINKED ISSUE #290: Test nightly against PyBaMM develop
### Feature description

Add a workflow to nightly test against PyBaMM `develop`. This will most likely be a stop-gap until the shared conda nightly builds with PyBaMM are completed (organised by @agriyakhetarpal). 

### Motivation

Allows us to capture how breaking changes from PyBaMM will affect PyBOP.

### Possible implementation

Update `pyproject.toml` within github action before running the test suite.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by BradyPlanden**
# Description

Fixes workflow deployed in #291. 

## Issue reference
Fixes #290 

## Review
Before you mark your PR as ready for review, please ensure that you've considered the following:
- Updated the [CHANGELOG.md](https://github.com/pybop-team/PyBOP/blob/develop/CHANGELOG.md) in reverse chronological order (newest at the top) with a concise description of the changes, including the PR number.
- Noted any breaking changes, including details on how it might impact existing functionality.

## Type of change
- [ ] New Feature: A non-breaking change that adds new functionality.
- [ ] Optimization: A code change that improves performance.
- [ ] Examples: A change to existing or additional examples.
- [ ] Bug Fix: A non-breaking change that addresses an issue.
- [ ] Documentation: Updates to documentation or new documentation for new features.
- [ ] Refactoring: Non-functional changes that improve the codebase.
- [ ] Style: Non-functional changes related to code style (formatting, naming, etc).
- [ ] Testing: Additional tests to improve coverage or confirm functionality.
- [ ] Other: (Insert description of change)

# Key checklist:

- [ ] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybop-team/PyBOP/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [ ] All unit tests pass: `$ nox -s tests`
- [ ] The documentation builds: `$ nox -s doctest`

You can run integration tests, unit tests, and doctests together at once, using `$ nox -s quick`.

## Further checks:
- [ ] Code is well-commented, especially in complex or unclear areas.
- [ ] Added tests that prove my fix is effective or that my feature works.
- [ ] Checked that coverage remains or improves, and added tests if necessary to maintain or increase coverage.

Thank you for contributing to our project! Your efforts help us to deliver great software.

### CODE REVIEW

**Comment by agriyakhetarpal** [comment]
Should we add the automated issue action in a separate PR? I thought that you were going to do it in the same PR, but you merged it :) We can also do it later when PyBaMM gets ready with the nightlies.

**Comment by BradyPlanden** [comment]
Fair shout, I'm happy for it to be added here and we can update the PR (or create a new one). I wanted to get the workflow in before travelling next week so pushed it through. At least now something is in a develop. Apologies for the quick trigger!

**Comment by agriyakhetarpal** [comment]
No worries! I think we can merge this one – I'll create a new PR and add it there.

**Review by agriyakhetarpal — APPROVED** [review]
Oops, forgot to add my above comment as a review. Already approved from my end :) thanks!

**Pull request merged**
