### PR TITLE
Release v24.3.1

### LINKED ISSUE #368: Release v24.3.1
As today's Numpy 2.0 release introduces breakable changes to the functionality of Pints, a patch release of v24.3 is required. The relevant branch for this release is: https://github.com/pybop-team/PyBOP/tree/v24.3.1

### PR DESCRIPTION
**Pull request by BradyPlanden**
# Description

Patch release for v24.3, upper pins Numpy to < 2.0.

## Issue reference
Fixes #368 
## Review
Before you mark your PR as ready for review, please ensure that you've considered the following:
- Updated the [CHANGELOG.md](https://github.com/pybop-team/PyBOP/blob/develop/CHANGELOG.md) in reverse chronological order (newest at the top) with a concise description of the changes, including the PR number.
- Noted any breaking changes, including details on how it might impact existing functionality.

## Type of change
- [ ] New Feature: A non-breaking change that adds new functionality.
- [ ] Optimization: A code change that improves performance.
- [ ] Examples: A change to existing or additional examples.
- [X] Bug Fix: A non-breaking change that addresses an issue.
- [ ] Documentation: Updates to documentation or new documentation for new features.
- [ ] Refactoring: Non-functional changes that improve the codebase.
- [ ] Style: Non-functional changes related to code style (formatting, naming, etc).
- [ ] Testing: Additional tests to improve coverage or confirm functionality.
- [ ] Other: (Insert description of change)

# Key checklist:

- [ ] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybop-team/PyBOP/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [ ] All unit tests pass: `$ nox -s tests`
- [ ] The documentation builds: `$ nox -s doctest`

You can run integration tests, unit tests, and doctests together at once, using `$ nox -s quick`.

## Further checks:
- [ ] Code is well-commented, especially in complex or unclear areas.
- [ ] Added tests that prove my fix is effective or that my feature works.
- [ ] Checked that coverage remains or improves, and added tests if necessary to maintain or increase coverage.

Thank you for contributing to our project! Your efforts help us to deliver great software.

### CODE REVIEW

**Comment by BradyPlanden** [comment]
In it's current form, this PR is expected to fail due to tenacity's 8.4.0 release. I think this should be yanked or patched fairly quickly (see: https://github.com/jd/tenacity/pull/474), so I am leaving the top pin out of this PR/release.

**Comment by agriyakhetarpal** [comment]
`tenacity` v8.4.1 is out now. PyBaMM will soon provide the upper pin on NumPy v2, and I hope we'll remove it with either a patch v24.5.1 release or in the release candidate stage so that the stable version doesn't have it – we will most likely keep the pin in v24.5rc0. My only suggestion would be that if PyBOP does keep the upper pin here, it removes it in a further v24.3.2 and not with v24.5. :)

**Comment by BradyPlanden** [comment]
Just to add, I'm happy to have other fixes in this release if anyone has anything they would like included!

**Comment by agriyakhetarpal** [comment]
Ah, I have been working on the docs, but I don't think I'll be able to make them ready in time –  they would be better off in the v24.5 release.

**Review by NicolaCourtier — APPROVED** [review]
Thanks very much @BradyPlanden, looks good to me!

**Pull request merged**
