### PR TITLE
#282 Restructure `examples/` directory

### LINKED ISSUE #282: Restructure examples directory
### Feature description

The current examples directory includes a variety of unordered workflows. This should be restructured to provide a clearer entry point for users looking for specific functionality. I propose we do something like:

- Optimisation Type (Fitting, Design Optim., etc.)
   - `{model}_{cost function}.py`
   
For both `examples/notebooks/` and `examples/scripts/`. In this restructure we can reduce the total number of examples by using multipler optimisers for each `{model}_{cost function}.py`. This would look something like our integration test `test_parameterisation.py`.

### Motivation

_No response_

### Possible implementation

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by arjxn-py**
# Description
This PR restructures the examples directory to provide a more organized and user-friendly entry point for users seeking specific functionality.

## Issue reference
Fixes #282 

## Review
Before you mark your PR as ready for review, please ensure that you've considered the following:
- Updated the [CHANGELOG.md](https://github.com/pybop-team/PyBOP/blob/develop/CHANGELOG.md) in reverse chronological order (newest at the top) with a concise description of the changes, including the PR number.
- Noted any breaking changes, including details on how it might impact existing functionality.

## Type of change
- [ ] New Feature: A non-breaking change that adds new functionality.
- [ ] Optimization: A code change that improves performance.
- [x] Examples: A change to existing or additional examples.
- [ ] Bug Fix: A non-breaking change that addresses an issue.
- [ ] Documentation: Updates to documentation or new documentation for new features.
- [ ] Refactoring: Non-functional changes that improve the codebase.
- [ ] Style: Non-functional changes related to code style (formatting, naming, etc).
- [ ] Testing: Additional tests to improve coverage or confirm functionality.
- [ ] Other: (Insert description of change)

# Key checklist:

- [ ] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybop-team/PyBOP/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for how to set this up to run automatically when committing locally, in just two lines of code)
- [ ] All unit tests pass: `$ nox -s tests`
- [ ] The documentation builds: `$ nox -s doctest`

You can run integration tests, unit tests, and doctests together at once, using `$ nox -s quick`.

## Further checks:
- [ ] Code is well-commented, especially in complex or unclear areas.
- [ ] Added tests that prove my fix is effective or that my feature works.
- [ ] Checked that coverage remains or improves, and added tests if necessary to maintain or increase coverage.

### CODE REVIEW

**Comment by arjxn-py** [comment]
I think this is ready for an initial review, I've covered most of the notebooks and scripts in [#282-comment](https://github.com/pybop-team/PyBOP/issues/282#issuecomment-2167505750), example tests might be failing right now which i'll work on to fix. 
However there's one notebook that's repeating in `Getting Started/` & `Design Optimisation/` i.e. `spm_electrode_design`

**Comment by arjxn-py** [comment]
Tests are also passing now.
cc: @NicolaCourtier @BradyPlanden

**Comment by NicolaCourtier** [comment]
Hi @arjxn-py, thanks for sharing your progress on this issue! A few comments:
- please consider whether to put scripts and notebooks together in the new folder structure or keep separate (currently the new folders are all stored within `examples/notebooks` which will make the scripts difficult to find)
- let's merge and rename `LG_M50_ECM/data` into just `LGM50_data`
- the new `plotting_a_dataset.ipynb` is more like what I was imagining for `importing_a_pybamm_model` (importing, running and plotting the result of a PyBaMM model)
- just "plotting a dataset" would be like the start of `LGM_50_identification`

Thanks again, please let me know if any questions and request a review when you are ready.

**Comment by NicolaCourtier** [comment]
This branch has become outdated - issue #282 on the restructuring of the examples directory has been resolved by #559.
Please open a new issue if you would like to improve the examples!

**Pull request closed without merging**
